openapi: 3.0.3
info:
  title: PaqueteriaCZ API
  version: 1.0.0
  description: API para gestión de pedidos y autenticación (login JWT)
servers:
  - url: http://localhost/paqueteriacz
paths:
  /api/auth/login:
    post:
      summary: Autenticar usuario y obtener token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Token generado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
  /api/pedidos/listar:
    get:
      summary: Obtener listado de pedidos (extendido)
      responses:
        '200':
          description: Listado de pedidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
  /api/pedidos/crear:
    post:
      summary: Crear un nuevo pedido (requiere Authorization)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numero_orden:
                  type: integer
                destinatario:
                  type: string
                telefono:
                  type: string
                producto:
                  type: string
                cantidad:
                  type: integer
                coordenadas:
                  type: string
                direccion:
                  type: string
              required: [numero_orden, destinatario, telefono, producto]
      responses:
        '200':
          description: Pedido creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: integer
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
